version: build{build}

image: Visual Studio 2017

environment:
  matrix:
    - QT_PATH : C:\Qt\5.11.2\msvc2017_64\bin
      PLATFORM : amd64
      OUTPUT_BIN_DIR : bin64
    - QT_PATH : C:\Qt\5.11.2\msvc2015\bin
      PLATFORM : x86
      OUTPUT_BIN_DIR : bin32

clone_folder: c:\dev\labrador
clone_depth: 1
configuration: Release

branches:
  only:
    - master

init:
  - set PATH=%QT_PATH%;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%

before_build:
  - cd c:\dev\labrador\Desktop_Interface 

build_script:
  - qmake
  - nmake

after_build:
  - windeployqt bin\Labrador.exe
  - del bin\vcredist*.exe
  - del bin\*.pdb
  - cd C:\dev
  - git clone --depth 1 https://github.com/EspoTek/Labrador-win-builder
  - xcopy /i /s /y c:\dev\labrador\Desktop_Interface\bin %OUTPUT_BIN_DIR%
  - git add %OUTPUT_BIN_DIR%
  - git commit -a -m "Automatic update from main Labrador repository"
  - git push

artifacts:
  - path: Desktop_Interface\bin
    name: Labrador_%PLATFORM%
    type: zip
