version: build{build}

platform: amd64

clone_folder: c:\dev\labrador
clone_depth: 1

init:
  - set PATH=C:\Qt\5.11\msvc2013_64\bin;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%

before_build:
  - cd c:\dev\labrador\Desktop_Interface 

build_script:
  - qmake
  - nmake 
