version: build{build}

image: Visual Studio 2017

platform: amd64

clone_folder: c:\dev\labrador
clone_depth: 1

init:
  - set PATH=C:\Qt\5.11.2\msvc2017_64\bin;%PATH%

before_build:
  - cd c:\dev\labrador\Desktop_Interface 

build_script:
  - qmake
  - nmake 
