version: build{build}

image: Visual Studio 2017

platform: amd64

clone_folder: c:\dev\labrador
clone_depth: 1

init:
  - set PATH=C:\Qt\5.11.2\msvc2017_64\bin;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%

before_build:
  - cd c:\dev\labrador\Desktop_Interface 

build_script:
  - qmake
  - nmake 

after_build:
  - windeployqt bin/Labrador.exe

artifacts:
  - path: c:\dev\labrador\Desktop_Interface\bin
    name: Labrador_x64
    type: zip
