version: build{build}

image: Visual Studio 2017

environment:
  matrix:
    - VCVARSALL : C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      QT_PATH : C:\Qt\5.11.2\msvc2017_64\bin
      PLATFORM : amd64
    - VCVARSALL : C:\Program Files (x86)\Microsoft Visual Studio 13.0\VC\vcvarsall.bat
      QT_PATH : C:\Qt\5.11.2\msvc2015_32\bin
      PLATFORM : x86

clone_folder: c:\dev\labrador
clone_depth: 1
configuration: Release

branches:
  only:
    - master

init:
  - set PATH=%QT_PATH%;%PATH%
  - call "%VCVARSALL%" %PLATFORM%

before_build:
  - cd c:\dev\labrador\Desktop_Interface 

build_script:
  - qmake
  - nmake

after_build:
  - windeployqt bin/Labrador.exe

artifacts:
  - path: Desktop_Interface\bin
    name: Labrador_%PLATFORM%
    type: zip
